# Generated by Django 4.0.1 on 2022-02-11 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=100)),
                ('telephone', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(default='', max_length=50)),
                ('carreer', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_name', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('date', models.CharField(default='', max_length=50)),
                ('cid', models.CharField(default='', max_length=13)),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(default='', max_length=13)),
                ('gid', models.CharField(default='', max_length=13)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('gid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('brand', models.CharField(default='', max_length=60)),
                ('model', models.CharField(default='', max_length=60)),
                ('price', models.FloatField(default=0.0)),
                ('net', models.IntegerField(default=0)),
                ('property', models.CharField(default='', max_length=50)),
                ('goodsCategory', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myInfo.goodscategory')),
            ],
        ),
    ]
